[package]
name = "wasm-interp"
version = "0.1.0"
authors = ["Bill Fraser <wfraser@codewise.org>"]
edition = "2018"

[dependencies]
log = "0.4"
wasm-binary = { path = "../wasm-binary" }

[dev-dependencies]
env_logger = "*"
