[package]
name = "demo"
version = "0.1.0"
authors = ["Bill Fraser <wfraser@codewise.org>"]
edition = "2018"

[dependencies]
stderrlog = "0.5"
wasm-binary = { path = "../wasm-binary" }
wasm-interp = { path = "../wasm-interp" }
